name: CI + Security (Org)

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '17 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  checks: write
  actions: read
  pull-requests: write

jobs:
  org_ci:
    uses: your-org/.github/.github/workflows/org-ci-required.yml@main
    secrets: inherit
