name: CI + Security (Org)

on:
  push:
  pull_request:
  merge_group:
  schedule:
    - cron: '17 3 * * *' # daily 03:17 UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  checks: write
  actions: read
  pull-requests: write
  issues: write

jobs:
  org_ci:
    uses: Nova-s-Personal-Organization/.github/.github/workflows/org-ci-required.yml@main
    secrets: inherit
