version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule: { interval: weekly }
    open-pull-requests-limit: 10
    groups:
      minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: pip
    directory: "/"
    schedule: { interval: weekly }
  - package-ecosystem: gomod
    directory: "/"
    schedule: { interval: weekly }
  - package-ecosystem: maven
    directory: "/"
    schedule: { interval: weekly }
  - package-ecosystem: gradle
    directory: "/"
    schedule: { interval: weekly }
  - package-ecosystem: cargo
    directory: "/"
    schedule: { interval: weekly }
  - package-ecosystem: nuget
    directory: "/"
    schedule: { interval: weekly }
  - package-ecosystem: bundler
    directory: "/"
    schedule: { interval: weekly }
