name: Detect project languages and tools
description: Detects common project types and CodeQL languages
outputs:
  has_node:
    description: Project includes Node.js
  has_python:
    description: Project includes Python
  has_go:
    description: Project includes Go
  has_java_maven:
    description: Project includes Java (Maven)
  has_java_gradle:
    description: Project includes Java (Gradle)
  has_rust:
    description: Project includes Rust
  has_dotnet:
    description: Project includes .NET
  has_ruby:
    description: Project includes Ruby
  codeql_languages_json:
    description: JSON array of CodeQL languages to scan
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -euo pipefail

        # Helper to check if any file exists in git
        has_files() {
          git ls-files -z | tr '\0' '\n' | grep -E -q "$1"
        }

        # Basic manifest checks
        has_node=false
        has_python=false
        has_go=false
        has_java_maven=false
        has_java_gradle=false
        has_rust=false
        has_dotnet=false
        has_ruby=false

        if has_files '(^|/)(package\.json|pnpm-lock\.yaml|yarn\.lock)$'; then has_node=true; fi
        if has_files '(^|/)(requirements(\.txt)?|Pipfile|poetry\.lock|pyproject\.toml)$|\.py$'; then has_python=true; fi
        if has_files '(^|/)go\.mod$|\.go$'; then has_go=true; fi
        if has_files '(^|/)pom\.xml$'; then has_java_maven=true; fi
        if has_files '(^|/)build\.gradle(\.kts)?$'; then has_java_gradle=true; fi
        if has_files '(^|/)Cargo\.toml$'; then has_rust=true; fi
        if has_files '(\.sln$|\.csproj$)'; then has_dotnet=true; fi
        if has_files '(^|/)Gemfile$|\.rb$'; then has_ruby=true; fi

        echo "has_node=$has_node" >> "$GITHUB_OUTPUT"
        echo "has_python=$has_python" >> "$GITHUB_OUTPUT"
        echo "has_go=$has_go" >> "$GITHUB_OUTPUT"
        echo "has_java_maven=$has_java_maven" >> "$GITHUB_OUTPUT"
        echo "has_java_gradle=$has_java_gradle" >> "$GITHUB_OUTPUT"
        echo "has_rust=$has_rust" >> "$GITHUB_OUTPUT"
        echo "has_dotnet=$has_dotnet" >> "$GITHUB_OUTPUT"
        echo "has_ruby=$has_ruby" >> "$GITHUB_OUTPUT"

        # Build CodeQL languages list (supported: cpp, csharp, go, java-kotlin, javascript-typescript, python, ruby, swift)
        langs=()
        $has_node && langs+=("javascript-typescript")
        $has_python && langs+=("python")
        $has_go && langs+=("go")
        if $has_java_maven || $has_java_gradle; then langs+=("java-kotlin"); fi
        $has_dotnet && langs+=("csharp")
        $has_ruby && langs+=("ruby")
        # (Rust not supported by CodeQL at this time)

        # Unique and JSON-encode
        if [ ${#langs[@]} -eq 0 ]; then
          echo 'codeql_languages_json=[]' >> "$GITHUB_OUTPUT"
        else
          printf -v json '[%s]' "$(printf '"%s",' "${langs[@]}" | sed 's/,$//')"
          echo "codeql_languages_json=$json" >> "$GITHUB_OUTPUT"
        fi
